CameraPanningCursor
float CameraPanningCursor.cameraLerpSpeed
Referenced by TranslateWithMousePos.
int CameraPanningCursor.zoomMin
Referenced by ReshiftCam.
int CameraPanningCursor.zoomMax
Referenced by ReshiftCam.
float CameraPanningCursor.keyboardLerpSpeed
Referenced by TranslateWithKeyboard.
float CameraPanningCursor.zoomSpeed
Referenced by ZoomWithMouseWheel.
float CameraPanningCursor.bounceSpeed
Referenced by ReshiftCam.
GameObject CameraPanningCursor.playArea
Referenced by SetCameraBounds, Start.
Camera CameraPanningCursor.camera
Referenced by IsInsideBound, ReshiftCam, Start, TranslateWithKeyboard, TranslateWithMousePos.
Vector2 CameraPanningCursor.cameraBoundingX
Referenced by ReshiftCam.
Vector2 CameraPanningCursor.cameraBoundingY
Referenced by ReshiftCam.
InputDetection CameraPanningCursor.inputDetection
Referenced by TranslateWithKeyboard, TranslateWithMousePos, Update.
Vector2 CameraPanningCursor.CameraBoundingX
Referenced by IsInsideBound, ReshiftCam, SetCameraBounds, Start.
Vector2 CameraPanningCursor.CameraBoundingY
Referenced by Start.
Vector2 [] CameraPanningCursor.CameraFOVBounds
Referenced by ReshiftCam.
void CameraPanningCursor.Start()
References camera, CameraBoundingX, CameraBoundingY, GetTileMapSize, playArea, ReshiftCam, SetCameraBounds.
IEnumerator CameraPanningCursor.ReshiftCam(float tileSize)
Coroutine to reshift camera position when camera is out of predefined bound
boundingX Play area left and right width bound boundingY Play area upmost and downmost bound returns>Returns null each frame as base condition for coroutine
References bounceSpeed, camera, cameraBoundingX, CameraBoundingX, cameraBoundingY, CameraFOVBounds, zoomMax, zoomMin.
Referenced by LateUpdate, Start.
void CameraPanningCursor.Update()
References InputDetection.BeginClickEvent, inputDetection, InputDetection.IsKeyboardInput, TranslateWithKeyboard, TranslateWithMousePos, ZoomWithMouseWheel.
void CameraPanningCursor.LateUpdate()
References IsInsideBound, ReshiftCam.
void CameraPanningCursor.TranslateWithMousePos()
Main function to perform camera panning, function is called when camera is not out of play area bound, uses Vector3.Lerp()
Vector3.Lerp(camera.transform.position, mousePosToWorld, cameraLerpSpeed*Time.deltaTime);
References camera, cameraLerpSpeed, InputDetection.DeltaSwipe, inputDetection, IsInsideBound.
Referenced by Update.
void CameraPanningCursor.ZoomWithMouseWheel()
Main function to perform camera zooming, function is called when camera size is inside a predefined range, uses Mathf.Lerp()
Mathf.Lerp(camera.orthographicSize, zoomThreshold, time);
References zoomSpeed.
Referenced by Update.
void CameraPanningCursor.TranslateWithKeyboard()
References camera, InputDetection.DetectingKeyboardInputEvent, inputDetection, keyboardLerpSpeed.
Referenced by Update.
Vector3 CameraPanningCursor.GetTileMapSize(Tilemap playArea)
Get the size of tilemap using Bounds class
playArea Play area that contains Tilemap component returns>Size of tilemap as vector3
Referenced by SetCameraBounds, Start.
bool CameraPanningCursor.IsInsideBound()
Check if camera is inside play area bound
CameraBoundingX Play area left and right width bound CameraBoundingY Play area upmost and downmost bound returns>True if camera position is inside play area.Otherwuse false
References camera, CameraBoundingX.
Referenced by LateUpdate, TranslateWithMousePos.
void CameraPanningCursor.SetCameraBounds(float boundRight)
TO DO, Does not sync well with the given bounds, how to convert?
References CameraBoundingX, GetTileMapSize, playArea.
Referenced by Start.