PauseMenuScript
bool PauseMenuScript.isGameOver
Referenced by Start, TurnOffPause, TurnOnPause, Update.
GameObject PauseMenuScript.PauseMenu
GameObject PauseMenuScript.PlayMenu
void PauseMenuScript.Update()
References isGameOver, TurnOffPause, TurnOnPause.
void PauseMenuScript.Start()
References isGameOver.
void PauseMenuScript.TurnOnPause()
References isGameOver.
Referenced by Update.
void PauseMenuScript.TurnOffPause()
References isGameOver.
Referenced by UnpuaseButton, Update.
void PauseMenuScript.GoToMainMenuButton()
void PauseMenuScript.UnpuaseButton()
References TurnOffPause.