PlayerStats
int PlayerStats.MaxLives
Referenced by Start.
int PlayerStats.CurrentLives
Referenced by CheckLife, RemoveLife, Start.
Text PlayerStats.crystalText_Red
Text PlayerStats.crystalText_Blue
Text PlayerStats.crystalText_Green
Text PlayerStats.crystalText_Yellow
GameObject PlayerStats.skillGameObject_Red
int PlayerStats.crystalsOwned_Red
Referenced by UpdateCrystalUI, UpdateCrystalValues.
int PlayerStats.crystalsOwned_Blue
Referenced by UpdateCrystalUI, UpdateCrystalValues.
int PlayerStats.crystalsOwned_Green
Referenced by UpdateCrystalUI, UpdateCrystalValues.
int PlayerStats.crystalsOwned_Yellow
Referenced by UpdateCrystalUI, UpdateCrystalValues.
bool PlayerStats.skillReady_Red
Referenced by UpdateSkillCooldowns, UpdateSkillUI.
float PlayerStats.crystalsExtra_Red
Referenced by UpdateCrystalValues.
float PlayerStats.crystalsExtra_Blue
Referenced by UpdateCrystalValues.
float PlayerStats.crystalsExtra_Green
Referenced by UpdateCrystalValues.
float PlayerStats.crystalsExtra_Yellow
Referenced by UpdateCrystalValues.
float PlayerStats.crystalsPerSecond_Red
Referenced by UpdateCrystalValues.
float PlayerStats.crystalsPerSecond_Blue
Referenced by UpdateCrystalValues.
float PlayerStats.crystalsPerSecond_Green
Referenced by UpdateCrystalValues.
float PlayerStats.crystalsPerSecond_Yellow
Referenced by UpdateCrystalValues.
float PlayerStats.skillCountdown_Red
Referenced by UpdateSkillCooldowns.
float PlayerStats.skillCooldown_Red
Referenced by UpdateSkillCooldowns.
void PlayerStats.Start()
References CurrentLives, MaxLives, UpdateCrystalValues.
void PlayerStats.Update()
References UpdateSkillCooldowns, UpdateSkillUI.
void PlayerStats.RemoveLife(int i)
References CurrentLives, GameOver.
int PlayerStats.CheckLife()
References CurrentLives.
void PlayerStats.GameOver()
Referenced by RemoveLife.
void PlayerStats.UpdateSkillCooldowns()
Undocumented
References skillCooldown_Red, skillCountdown_Red, skillReady_Red.
Referenced by Update.
IEnumerator PlayerStats.UpdateCrystalValues()
Undocumented
References crystalsExtra_Blue, crystalsExtra_Green, crystalsExtra_Red, crystalsExtra_Yellow, crystalsOwned_Blue, crystalsOwned_Green, crystalsOwned_Red, crystalsOwned_Yellow, crystalsPerSecond_Blue, crystalsPerSecond_Green, crystalsPerSecond_Red, crystalsPerSecond_Yellow, GameOverScript.isGameOver, UpdateCrystalUI.
Referenced by Start.
void PlayerStats.UpdateCrystalUI()
Update Crystal UI elements
References crystalsOwned_Blue, crystalsOwned_Green, crystalsOwned_Red, crystalsOwned_Yellow.
Referenced by UpdateCrystalValues.
void PlayerStats.UpdateSkillUI()
Update Crystal UI elements
References skillReady_Red.
Referenced by Update.