MapBoundsUpdater
MapBound MapBoundsUpdater.mapBounds
Referenced by CheckForMatchingBounds, MoveMapBounds, WaitTime.
GameObject MapBoundsUpdater.TileMap
TileBase MapBoundsUpdater.barrierTile
Referenced by MoveMapBounds.
GameObject MapBoundsUpdater.SpawnManager
GameObject MapBoundsUpdater.Camera
int MapBoundsUpdater.WaveCounter
Referenced by MoveMapBounds, RestoreTiles, WaitTime.
int MapBoundsUpdater.time
Referenced by WaitTime.
TileNodes MapBoundsUpdater.tileNodes
Referenced by Setup.
Tilemap MapBoundsUpdater.uniqueTilemap
Referenced by Setup.
WaveSystem.WaveManager MapBoundsUpdater.waveManger
Referenced by Setup.
CameraPanningCursor MapBoundsUpdater.cameraPanningCursor
Referenced by Setup.
List<int> MapBoundsUpdater.yValues
Referenced by MoveMapBounds, RestoreTiles, Setup.
int MapBoundsUpdater.minY
Referenced by Setup.
int MapBoundsUpdater.maxY
Referenced by Setup.
List<TileBase> MapBoundsUpdater.restorationTiles
Referenced by RestoreTiles, Setup.
void MapBoundsUpdater.Start()
References CheckForMatchingBounds, MoveMapBounds, Setup, WaitTime.
void MapBoundsUpdater.Setup()
Setups up all of the lists, refferences and y value sizing.
References cameraPanningCursor, maxY, minY, restorationTiles, tileNodes, uniqueTilemap, waveManger, yValues.
Referenced by Start.
void MapBoundsUpdater.CheckForMatchingBounds()
Error checking for invalid setup.
References mapBounds.
Referenced by Start.
IEnumerator MapBoundsUpdater.WaitTime()
UNDOCUMENTED
References mapBounds, MoveMapBounds, MapBound.positionX, time, WaveCounter.
Referenced by Start.
void MapBoundsUpdater.MoveMapBounds()
Move the map boudaires over to the next X position provided by the MapBound Scriptable Object
References barrierTile, mapBounds, MapBound.positionX, RestoreTiles, WaveCounter, yValues.
Referenced by Start, WaitTime.
void MapBoundsUpdater.MoveCameraBounds()
UNDOCUMENTED
void MapBoundsUpdater.RestoreTiles()
UNDOCUMENTED
References restorationTiles, WaveCounter, yValues.
Referenced by MoveMapBounds.