WaveSystem::WaveManager
TileNodes WaveSystem.WaveManager.tiles
Referenced by WaveSystem.WaveManager.Start.
GameObject WaveSystem.WaveManager.spawnSingleEnemy
bool WaveSystem.WaveManager.enableSpawning
WaveData [] WaveSystem.WaveManager.waves
Referenced by WaveSystem.WaveManager.AllWaveCompleted, WaveSystem.WaveManager.SpawnSingleEnemyPerWave, WaveSystem.WaveManager.Start.
GameObject WaveSystem.WaveManager.waveParent
Referenced by WaveSystem.WaveManager.SpawnSingleEnemyPerWave.
bool WaveSystem.WaveManager.EnableSpawning
Referenced by WaveSystem.WaveManager.SpawnSingleEnemyPerWave, WaveSystemTimer.UIConnection, SoundManager.Update, WaveSystem.WaveManager.Update.
List<Vector3> WaveSystem.WaveManager.NodeSpawnPosition
WaveData WaveSystem.WaveManager.CurrentWave
Referenced by WaveSystem.WaveManager.SpawnSingleEnemyPerWave, WaveSystem.WaveManager.Start, WaveSystem.WaveManager.Update.
int WaveSystem.WaveManager.WaveIndex
Referenced by WaveSystemTimer.UIConnection.
String WaveSystem.WaveManager.TimeUntilNextWave
Referenced by WaveSystemTimer.UIConnection.
String WaveSystem.WaveManager.WaveTimer
WaveData WaveSystem.WaveManager.currentWave
List<Vector3> WaveSystem.WaveManager.selectedNodeSpawnPosition
Timer WaveSystem.WaveManager.currentTimer
Referenced by WaveSystem.WaveManager.SpawnSingleEnemyPerWave, WaveSystem.WaveManager.Update.
int WaveSystem.WaveManager.waveIndex
Referenced by WaveSystem.WaveManager.AllWaveCompleted, WaveSystem.WaveManager.SpawnSingleEnemyPerWave.
TileNodes WaveSystem.WaveManager.tileNodes
Referenced by WaveSystem.WaveManager.Start.
CursorSelection WaveSystem.WaveManager.cursorSelection
Referenced by WaveSystem.WaveManager.Start.
SoundManager WaveSystem.WaveManager.soundManager
void WaveSystem.WaveManager.Awake()
void WaveSystem.WaveManager.Start()
References WaveSystem.WaveManager.CurrentWave, WaveSystem.WaveManager.cursorSelection, WaveSystem.WaveManager.MakeParent, TileNodes.pathData, PathsData.paths, WaveSystem.WaveManager.SpawnSingleEnemyPerWave, WaveSystem.WaveManager.tileNodes, WaveSystem.WaveManager.tiles, WaveSystem.WaveManager.waves.
void WaveSystem.WaveManager.Update()
References WaveSystem.WaveManager.AllWaveCompleted, WaveSystem.WaveManager.currentTimer, WaveSystem.WaveManager.CurrentWave, WaveSystem.WaveManager.EnableSpawning, WaveSystem.WaveManager.InstantiateNewTimer, Timer.NextWaveCountdown, WaveData.TimeUntilSpawn, Timer.WaveCountdown, WaveData.WaveTimer.
void WaveSystem.WaveManager.MakeParent()
Create new parent gameobject to store enemy info
Referenced by WaveSystem.WaveManager.Start.
void WaveSystem.WaveManager.InstantiateNewTimer(float timeUntilSpawn, float waveTimer, ref Timer timer)
Create a new timer instance when a wave is finished
timeUntilSpawn Timer between wave until next wave starts waveTimer Timer for current wave timer ref variable timer to reference the timer instance
Referenced by WaveSystem.WaveManager.SpawnSingleEnemyPerWave, WaveSystem.WaveManager.Update.
Boolean WaveSystem.WaveManager.AllWaveCompleted()
Check if all waves in waves[] have been processed
returns>Returns true if reaches the end of array
References WaveSystem.WaveManager.waveIndex, WaveSystem.WaveManager.waves.
Referenced by WaveSystem.WaveManager.SpawnSingleEnemyPerWave, WaveSystem.WaveManager.Update.
IEnumerator WaveSystem.WaveManager.SpawnSingleEnemyPerWave()
Main method for spawning a single type of enemy in multiple position
Use IEnumerator and must only be called in Start() /remarks>
References WaveSystem.WaveManager.AllWaveCompleted, WaveSystem.WaveManager.currentTimer, WaveSystem.WaveManager.CurrentWave, WaveSystem.WaveManager.EnableSpawning, WaveData.EnemyPrefab, WaveSystem.WaveManager.InstantiateNewTimer, WaveData.ParentGameobject, WaveData.Paths, WaveData.SpawnRate, Timer.TimeUntilNextSpawn, WaveData.TimeUntilSpawn, WaveSystem.WaveManager.waveIndex, WaveSystem.WaveManager.waveParent, WaveSystem.WaveManager.waves, WaveData.WaveTimer.
Referenced by WaveSystem.WaveManager.Start.