TowerShooting
ProjectileData TowerShooting.projectilePresetData
Referenced by GenerateProjectile.
List<EnemyScript> TowerShooting.MonstersToShoot
Referenced by Shoot, Start.
float TowerShooting.timeToReload
Referenced by Reload.
float TowerShooting.reloadProgress
Referenced by Reload.
bool TowerShooting.isReadyToShoot
Referenced by Reload, Shoot.
void TowerShooting.Start()
References MonstersToShoot.
void TowerShooting.Update()
References Reload, Shoot.
void TowerShooting.OnTriggerEnter2D(Collider2D collider)
UNDOCUMTNETED
void TowerShooting.Reload()
UNDOCUMTNETED
References isReadyToShoot, reloadProgress, timeToReload.
Referenced by Update.
void TowerShooting.Shoot()
UNDOCUMTNETED
References GenerateProjectile, isReadyToShoot, MonstersToShoot.
Referenced by Update.
void TowerShooting.GenerateProjectile(GameObject monster)
Data to use for making a projectile is tower upgarade -> adding the sill tree -> adding any other bonuses. The "projectilePresetData" is reset to a new version on tower upgrade.
References ProjectileData.projectilePrefab, projectilePresetData.
Referenced by Shoot.
void TowerShooting.OnTriggerExit2D(Collider2D collider)
UNDOCUMTNETED