SoundManager
AudioSource SoundManager.mainAudioSourceSoundtrack
Referenced by Update.
AudioSource SoundManager.mainAudioSourceUI
Referenced by PlayOnUIClick.
SoundObject [] SoundManager.soundClips
Referenced by PlaySpecificSound, Update.
bool SoundManager.IsMuteSoundtrack
Referenced by MuteSoundtrack.
bool SoundManager.IsMuteUI
Referenced by MuteUI.
bool SoundManager.ReturnControl
AudioClip SoundManager.currentClip
bool SoundManager.triggerOnLevelLoad
Referenced by OnLevelWasLoaded, OnScenceLoad, OnSceneLoaded, Update.
WaveManager SoundManager.waveManager
Referenced by Start, Update.
bool SoundManager.returnControl
Referenced by LoopThroughSoundList, Update.
void SoundManager.OnEnable()
References OnSceneLoaded.
void SoundManager.AutoDestroySelf()
Referenced by Start.
void SoundManager.Start()
References AutoDestroySelf, waveManager.
void SoundManager.OnLevelWasLoaded(int level)
References triggerOnLevelLoad.
void SoundManager.OnSceneLoaded(Scene scene, LoadSceneMode mode)
References triggerOnLevelLoad.
Referenced by OnEnable.
void SoundManager.OnScenceLoad()
References triggerOnLevelLoad.
void SoundManager.Update()
References WaveSystem.WaveManager.EnableSpawning, LoopThroughSoundList, mainAudioSourceSoundtrack, returnControl, soundClips, triggerOnLevelLoad, waveManager.
void SoundManager.LoopThroughSoundList(SoundObject[] clips)
References PlaySoundByName, returnControl.
Referenced by Update.
IEnumerator SoundManager.AudioVolumeDampeningOnLoad(AudioSource audioSource, float smallestLerpValue, float initialVolumeValue, float lerpTime)
void SoundManager.PlaySpecificSound(String soundName)
References PlaySoundByName, soundClips.
void SoundManager.PlayOnUIClick(SoundObject clip)
References mainAudioSourceUI.
void SoundManager.PlaySoundByName(SoundObject audioClip)
Referenced by LoopThroughSoundList, PlaySpecificSound.
void SoundManager.VolumeChangeSoundtrack(Slider slider)
void SoundManager.VolumeChangeUI(Slider slider)
void SoundManager.MuteUI()
References IsMuteUI.
void SoundManager.MuteSoundtrack()
References IsMuteSoundtrack.