TileNodes
Grid TileNodes.gridBase
Referenced by BuildHiddenNodes, LoopThroughTileset.
Tilemap TileNodes.uniqueTilemap
Tilemap TileNodes.hiddenTileMap
Referenced by HideTiles, PopupUI.ShowPopUpPanel, ShowTiles.
GameObject TileNodes.enemyPrefab
GameObject [] TileNodes.TileNodesPrefabs
Referenced by BuildHiddenNodes, LoopThroughTileset.
Tile [] TileNodes.WalkableTiles
Referenced by LoopThroughTileset.
Tile [] TileNodes.UnwalkableTiles
Referenced by LoopThroughTileset.
Tile [] TileNodes.SpawnTiles
Referenced by LoopThroughTileset.
Tile [] TileNodes.HiddenTiles
Referenced by BuildHiddenNodes.
Tile [] TileNodes.TowerTiles
Tile [] TileNodes.CrystalTiles
Referenced by LoopThroughTileset.
GameObject [,] TileNodes.nodes
Referenced by AddNodeToList, BuildHiddenNodes, BuildTable, FillNodeTable, generateNodes, LoopThroughTileset, SetNeigbours.
int TileNodes.SelectedPath
Referenced by Editor_SelectList, OnDrawGizmos.
List<WorldTile> TileNodes.selectedList
Referenced by Editor_SelectList.
PathsData TileNodes.pathData
Referenced by BuildTable, CheckBlockedPath, EnemyScript.DynamicPathRelocation, Editor_SelectList, OnDrawGizmos, BarrierDrag.OnEndDrag, WaveSystem.WaveManager.Start.
HiddenTileManager TileNodes.hiddenTileManager
Referenced by HideTiles, ShowTiles.
Dictionary<string, GameObject> TileNodes.dictionaryTest
List<GameObject> TileNodes.unsortedNodes
Referenced by BuildTable, FillNodeTable.
List<WorldTile> TileNodes.permanentSpawnPoints
Referenced by BuildTable.
float TileNodes.mapConstant
Referenced by BuildHiddenNodes, BuildTable, LoopThroughTileset.
GameObject [] TileNodes.parentNodes
Referenced by BuildTable, LoopThroughTileset.
GameObject TileNodes.parentHiddenNodes
Referenced by BuildHiddenNodes.
int TileNodes.maxGridX
Referenced by BuildTable, FillNodeTable.
void TileNodes.Awake()
References BuildTable, HideTiles.
void TileNodes.Start()
void TileNodes.Update()
References CheckBlockedPath.
void TileNodes.generateNodes()
Creates the nodes, places them in a table and sets each nodes neighbours
References FillNodeTable, LoopThroughTileset, nodes, SetNeigbours.
Referenced by BuildTable.
void TileNodes.LoopThroughTileset()
Scans tileset for tiles and places the corresponding tile node when it enconters one.
References CrystalTiles, gridBase, mapConstant, nodes, parentNodes, SpawnTiles, TileNodesPrefabs, UnwalkableTiles, WalkableTiles.
Referenced by generateNodes.
void TileNodes.FillNodeTable()
Checks tilemap for size of node array then places existing nodes in their corresponding place in the table.
References WorldTile.gridY, maxGridX, nodes, unsortedNodes.
Referenced by generateNodes.
void TileNodes.SetNeigbours()
For each tile in nodes[] checks the 4 surrounding tiles for neighbours
References nodes, SetNeigbour, WorldTile.walkable.
Referenced by generateNodes.
List<WorldTile> TileNodes.SetNeigbour(int x, int y, int width, int height, bool walkable)
Grab 4 surrounding tiles from all tilemaps and checks if they are neigbours
References AddNodeToList.
Referenced by SetNeigbours.
void TileNodes.AddNodeToList(List< WorldTile > list, int x, int y, bool currentWalkableState)
Error check each node and walkable status before adding to the WorldTile neighbours list
References nodes, WorldTile.walkable.
Referenced by SetNeigbour.
void TileNodes.OnDrawGizmos()
References pathData, PathsData.paths, SelectedPath.
void TileNodes.SetTileColor(Vector3Int tileCellPosition, Color color, Tilemap tileMap)
Set tile color as black to hide tiles and white to show tile
tileCellPosition Position of tile in tile map color Color of tile to be set tileMap Tilemap that contains hidden tiles
Referenced by HideTiles, ShowTiles.
void TileNodes.CheckBlockedPath()
References WorldTile.isBlockedBarrier, pathData, PathsData.paths.
Referenced by Update.
void TileNodes.BuildTable()
References generateNodes, mapConstant, maxGridX, nodes, parentNodes, pathData, permanentSpawnPoints, unsortedNodes.
Referenced by Awake.
void TileNodes.Editor_SelectList()
Allows you to see the list that is currently selected
References pathData, PathsData.paths, selectedList, SelectedPath.
void TileNodes.BuildHiddenNodes()
References gridBase, HiddenTiles, mapConstant, nodes, parentHiddenNodes, TileNodesPrefabs.
void TileNodes.SetSpawnStartPosFromSelected(ref List< WorldTile > permanentSpawnPoints, ref List< GameObject > selectedNodes)
void TileNodes.HideTiles()
tileList HiddenTileMananger object tileMap Tilemap that contains hidden tiles
References hiddenTileManager, hiddenTileMap, HiddenTileManager.list, TransformList.listOfNodes, SetTileColor.
Referenced by Awake.
void TileNodes.ShowTiles()
Reveal hidden area
Loop through each TransformList class to get required properties
References hiddenTileManager, hiddenTileMap, HiddenTileManager.list, TransformList.listOfNodes, SetTileColor.
void TileNodes.ShowTiles(Transform destructableTile)
Reveal hidden area
Loop through each TransformList class to get required properties destructableTile Node (associates with tile) that will reveal hidden area
References TransformList.breakableBlockPos, hiddenTileManager, hiddenTileMap, HiddenTileManager.list, TransformList.listOfNodes, SetTileColor.